#pragma once

#define TAPPING_TERM 175 
#define QUICK_TAP_TIMING 120
#define RETRO_TAPPING
#define TAPPING_TERM_PER_KEY
#define PERMISSIVE_HOLD
// #define HOLD_ON_OTHER_KEY_PRESS

#define DOUBLE_TAP_SHIFT_TURNS_ON_CAPS_WORD
